[tool.ruff]
line-length = 100
select = ["E","F","W","I"]
target-version = "py311"
exclude = ["venv",".venv","build","dist"]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
addopts = "-v --cov=app --cov-report=term-missing --cov-fail-under=80"
testpaths = ["tests"]
asyncio_default_fixture_loop_scope = "function"
